### ISSUE TITLE
Error appear randomly then using ollama with llama3.1 8B model

### ISSUE THREAD

**Issue by dibu28** [tcsenpai/multi1#4]
Error appear randomly then using ollama with llama3.1 8B model
On Windows

Error log:
2024-09-18 11:20:16,553 - multi1 - ERROR - Error generating response: 'title'
Traceback (most recent call last):
  File "H:\_multi1\multi1\app\main.py", line 84, in main
    for steps, total_thinking_time in generate_response(user_query, api_handler):
  File "H:\_multi1\multi1\app\utils.py", line 41, in generate_response
    steps.append((f"Step {step_count}: {step_data['title']}", step_data["content"], thinking_time))
                                        ~~~~~~~~~^^^^^^^^^
KeyError: 'title'


![Screenshot 2024-09-18 104712](https://github.com/user-attachments/assets/916f9e18-6669-455c-850d-d7eac5978f8e)

**Comment by tcsenpai** [comment]
I should have solved this (in my tests at least) by having a stricter control on litellm return format
