### ISSUE TITLE
Wrong and random answers for question: How many 'R's are in the word strawberry?

### ISSUE THREAD

**Issue by dibu28** [tcsenpai/multi1#5]
Wrong and random answers for question: "How many 'R's are in the word strawberry?"

Using model llama3.1 8B in ollama on Windows 11.

Model always gives different answers like 2 or 4. only sometimes it gives correct 3.

![image](https://github.com/user-attachments/assets/b8affa27-c254-45cd-990b-20c311f6c885)

**Comment by tcsenpai** [comment]
I think is either a LLM limitation or a prompting issues. I'll further test this with the same model/provider as llama3.1 8B should indeed be able to do it

**Comment by tcsenpai** [comment]
This should now be way better. Unfortunately, LLMs are unpredictable in their results but the current iteration should be way better. Can you confirm this @dibu28 ?

**Comment by dibu28** [comment]
Pulled changes. Tried 5 times but the result allways the same 2 letters:
And also error with title appears sometimes.

![image](https://github.com/user-attachments/assets/7836f055-7583-4e1f-a5de-6658a53fc6a5)

**Comment by tcsenpai** [comment]
I'll keep this open and try to fix it from a prompt point of view. If you manage to, feel free to push a PR.
