### ISSUE TITLE
I dont have idea what to do after treamlit main.py

### ISSUE THREAD

**Issue by raurio** [tcsenpai/multi1#8]
So? If i just turn on litellm will llm automatically use this system?

**Comment by tcsenpai** [comment]
streamlit should launch a browser window with the app running. Is this happening?

**Comment by tcsenpai** [comment]
You should have:

![image](https://github.com/user-attachments/assets/2dd39a6a-5987-40ec-b6aa-bd1c1bae2ad2)

Can you confirm this? Or else can you screenshot your terminal?

**Comment by raurio** [comment]
Oh it is differ from my cmd windows it doesnt say local url and network url
It just say welcome to streamlit!
If you would like to recieve helpful onboarding emails, news , offers, promotions, and the occasional swag, please enter your email address below. Otherwise, leave this field blank
Email:

It shows this

**Comment by tcsenpai** [comment]
Did you install requirements as in requirements.txt?

pip install -r requirements.txt

**Comment by raurio** [comment]
Yes i did in the multi1 folder

**Comment by raurio** [comment]
No way to connect to openwebui? Or please add this too

**Comment by tcsenpai** [comment]
> No way to connect to openwebui? Or please add this too

This repo does not use openwebui, is a standalone repo for a different purpose :) 

what does

`pip install litellm`

says?

**Comment by raurio** [comment]
I have litellm but it says no module 'litellm' maybe i have to delete and reinstall litellm.
Is there anyway using your program without litellm?
Just your program and ollama only

**Comment by tcsenpai** [comment]
> I have litellm but it says no module 'litellm' maybe i have to delete and reinstall litellm. Is there anyway using your program without litellm? Just your program and ollama only

Theoretically you can, you have to edit the main.py file to not import the LiteLLM handler.

I see you are using Windows. Can you try running the program with WSL2 ?

**Comment by raurio** [comment]
I ran it but sometimes at reasoning work it makes error but it doesnt mean it doesnt work totally. I think it depends on the questions. And you dont have plan to add more function like user have conversation like o1? Now it just answer once and  it doesnt remember previous chat at all as it restart the conversation per each of questions
